### ISSUE TITLE
Increase maximum data rate at the beginning of the DSP chain (ADC data) to 250 MHz

### ISSUE THREAD

**Issue by danielot** [lnls-dig/dsp-cores#34]
**Problem:** the current implementation and clock constraints of the BPM DSP chain are specified to run with 130 MHz data rate since the data source is the LTC2208 ADC. However, the DSP chain must be synthesizable at at least 250 MHz to cope with ISLA216P25 ADC.

**Comment by lerwys** [comment]
This was fixed a long time ago. We are using 250MHz constraint for a while.
