### ISSUE TITLE
[bpm_swap] Channel pairs can be wrongly de-swapped (inverted) when the user dynamically changes the swap enable signal

### ISSUE THREAD

**Issue by danielot** [lnls-dig/dsp-cores#38]
The output signal status[1..2]_o of the swap_cnt_top entity is a one-cycle pulse synchronized with the swap of the RFFE channels. This signal is used as reference in the en_i input of the inv_ch entity (which is the delayed version of the status signal) to trigger the de-swap of the ADC data streams.

The de-swap signal is generated essentially in the inv_proc process of the inv_ch entity, lines 71 and 72:
`
      elsif ((en = '1') and (en_old = '0')) then
        flag <= not flag;
`
It means inv_ch has no information of whether the channels are to be put in direct or inverted paths, but only the information of when to invert polarity of the de-swap signal.

When transients on the swap enable signal occurs, the swap signal which is actually driving the RFFE (generated inside swap_cnt_top) can jump to a new phase, for instance 180 degrees ahead. Since inv_ch will not follow this change in its internal state of the swap signal (flag), the result is a wrong de-swap of channels.

**Comment by lerwys** [comment]
This was done in d5b0068e773988666551e0eaf315c7b90d0f990e
