### ISSUE TITLE
[bpm_swap] Synchronize swapping process with FOFB CIC decimators

### ISSUE THREAD

**Issue by danielot** [lnls-dig/dsp-cores#39]
Each decimated sample of the CIC decimator shall reflect the history of input samples of one state of the RFFE swapping/de-swapping process (direct of inverted path). The output of the CIC filter should be alternating samples of direct and inverted paths.

**Comment by lerwys** [comment]
Done with commit a1b1c4c3c49df4faedf40f4166caba4b481b72f1
